# -*- coding: utf-8 -*-
"""GPT-Neo-2.7B Web UI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_jEKJZz4-x7_eDH6mep7LQ6fZv1RPqTQ
"""

!sudo apt-get update
!sudo apt-get install nvidia-cuda-toolkit

!pip install torch torchvision torchaudio torchtext
!pip install -q gradio
!pip install aitextgen

import gradio as gr
from aitextgen import aitextgen

ai = aitextgen(model="EleutherAI/gpt-neo-2.7B")

def ai_text(inp):
  res = ai.generate_one(max_length = 100, prompt = inp, no_repeat_ngram_size = 3) #repetition_penalty = 1.9)
  #print(type(generated_text))
  return res

ai_text("Americans can no longer make excuses for why they haven’t purchased life insurance.")

output_text = gr.outputs.Textbox()
gr.Interface(ai_text,"textbox", output_text, title="ai generated Blog with GPT-Neo",
             description="AI Generated Blog Content with GPT-Neo - via {aitextgen}").launch()

!pip freeze > requirements.txt